# Generated by Django 2.2.1 on 2019-07-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_assign', '0002_auto_20190722_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
